services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=usuario
      - DB_PASS=senha
      - DB_NAME=escolar
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: escolar
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  db_data: